# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GithubUserSearch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GithubUserSearch
   pod 'AFNetworking', :path => 'AFNetworking'

  target 'GithubUserSearchTests' do
    # Pods for testing
  end

end
